stg_table_name: CARD_ISSUANCE_REPORT
hash_keys:
  card_issuance_hash_key: ['card_barcode', 'contract_number', 'contract_date']
  card_issuance_sw_prop_hash_key: ['activation_date', 'transaction', 'card_type']

raw_stage_model_name: raw_card_issuance_tsretail
stage_model_name: v_card_issuance_tt_hsat_hub
raw_vault:
  hubs:
    - model_name: hub_card_issuance
      source_model: v_card_issuance_hsat_hub
      src_pk: card_issuance_hash_key
      distributed_by: card_issuance_hash_key
      src_nk: ['card_barcode', 'contract_number', 'contract_date']
      src_ldts: load_date
      src_source: source
      batch_target_tbl: dv.hub_card_issuance
  hsats:
    - model_name: hsat_card_issuance
      source_model: v_card_issuance_tt_hsat_hub
      src_pk: card_issuance_hash_key
      src_hashdiff: card_issuance_prop_hash_key
      distributed_by: card_issuance_hash_key
      src_payload: ['activation_date', 'transaction', 'card_type']
      src_eff: load_date
      src_ldts: load_date
      src_source: source
      batch_target_tbl: dv.hsat_card_issuance
base_dm:
  model_name: mart_card_issuance
  source_model_hub: hub_card_issuance
  source_model_hsat: hsat_card_issuance
  src_pk: card_issuance_hash_key
  distributed_by: card_issuance_hash_key
  unique_key: card_issuance_hash_key
  src_payload: ['activation_date', 'transaction', 'card_type']
  src_nk: ['card_barcode', 'contract_number', 'contract_date']
  src_eff: load_date
export_part2ch:
  tgt_table_name: card_issuance
  source_model: mart_card_issuance
  partitioning_key_date: contract_date