stg_table_name: CARD_ISSUANCE_REPORT_DETAILED
hash_keys:
  card_issuance_det_hash_key: ['registration_datetime', 'bank_contract_number']
  card_issuance_det_prop_hash_key: ['contract_month', 'contract_date', 'registration_month', 'bank_name', 'card_type', 'product_name', 'activation_flag_for_rtk', 'infrastructure_payment', 'bank_activation_flag', 'rtk_pos_code', 'card_barcode', 'issuing_employee_full_name', 'contract_application_number', 'rtk_application_channel', 'transaction_amount_from_issue_date', 'first_transaction_date', 'first_transaction_amount', 'card_closure_date', 'cash_withdrawal_credit_card', 'product_code', 'application_approval', 'rtk_application_number', 'outlet_address', 'approved_credit_amount', 'application_form', 'signing_method', 'first_dbo_login_date', 'is_return', 'application_status', 'final_status_from_bank']

raw_stage_model_name: raw_card_issuance_detailed_tsretail
stage_model_name: v_card_issuance_detailed_tt_hsat_hub
raw_vault:
  hubs:
    - model_name: hub_card_issuance_detailed
      source_model: v_card_issuance_detailed_tt_hsat_hub
      src_pk: card_issuance_det_hash_key
      distributed_by: card_issuance_det_hash_key
      src_nk: ['registration_datetime', 'bank_contract_number']
      src_ldts: load_date
      src_source: source
      batch_target_tbl: dv.hub_card_issuance_detailed
  hsats:
    - model_name: hsat_card_issuance_detailed
      source_model: v_card_issuance_detailed_tt_hsat_hub
      src_pk: card_issuance_det_hash_key
      src_hashdiff: card_issuance_det_prop_hash_key
      distributed_by: card_issuance_det_hash_key
      src_payload: ['contract_month', 'contract_date', 'registration_month', 'bank_name', 'card_type', 'product_name', 'activation_flag_for_rtk', 'infrastructure_payment', 'bank_activation_flag', 'rtk_pos_code', 'card_barcode', 'issuing_employee_full_name', 'contract_application_number', 'rtk_application_channel', 'transaction_amount_from_issue_date', 'first_transaction_date', 'first_transaction_amount', 'card_closure_date', 'cash_withdrawal_credit_card', 'product_code', 'application_approval', 'rtk_application_number', 'outlet_address', 'approved_credit_amount', 'application_form', 'signing_method', 'first_dbo_login_date', 'is_return', 'application_status', 'final_status_from_bank']
      src_eff: report_date
      src_ldts: load_date
      src_source: source
      batch_target_tbl: dv.hsat_card_issuance_detailed
base_dm:
  model_name: mart_card_issuance_detailed
  source_model_hub: hub_card_issuance_detailed
  source_model_hsat: hsat_card_issuance_detailed
  src_pk: card_issuance_det_hash_key
  distributed_by: card_issuance_det_hash_key
  unique_key: card_issuance_det_hash_key
  src_payload: ['contract_month', 'contract_date', 'registration_month', 'bank_name', 'card_type', 'product_name', 'activation_flag_for_rtk', 'infrastructure_payment', 'bank_activation_flag', 'rtk_pos_code', 'card_barcode', 'issuing_employee_full_name', 'contract_application_number', 'rtk_application_channel', 'transaction_amount_from_issue_date', 'first_transaction_date', 'first_transaction_amount', 'card_closure_date', 'cash_withdrawal_credit_card', 'product_code', 'application_approval', 'rtk_application_number', 'outlet_address', 'approved_credit_amount', 'application_form', 'signing_method', 'first_dbo_login_date', 'is_return', 'application_status', 'final_status_from_bank']
  src_nk: ['registration_datetime', 'bank_contract_number']
  src_eff: report_date
export_part2ch:
  tgt_table_name: card_issuance
  source_model: mart_card_issuance_detailed
  partitioning_key_date: contract_month