space_key: "RTKDT"
stg_hadoop:
  title: 'TSRETAIL_STG.CARD_ISSUANCE_REPORT (Отчет Банка по ДК/КК по выдачам карт)'
  parent_id_page: '2182845903' #  2422782607
  schema_name: 'TSRETAIL_STG'
  table_name: 'CARD_ISSUANCE_REPORT'
  table_desc: 'Отчет Банка по ДК/КК по выдачам и активациям карт банком и РТК'
  system_source: '//wd.mtsretail.ru//MSK/WorkData/Папка Обмена/Стангрет/Транзакция_ДК/DC_activation.xlsx' # topic_name 
  source_name: 'card_issuance_tsretail' # const for attr 'source'
  update_schedule: 'T-1'
  history_depth: '2026-05-01'
  archive_schema_table_name: 'tech_stg.xml_archive'
stg_gp:
  title: 'STG.CARD_ISSUANCE_REPORT (Отчет Банка по ДК/КК по выдачам карт)'
  parent_id_page: '2182845903' #  2422782607
  schema_name: 'STG'
  table_name: 'CARD_ISSUANCE_REPORT'
  table_desc: 'Отчет Банка по ДК/КК по выдачам и активациям карт банком и РТК'
  update_schedule: 'T-1'
  history_depth: '2026-05-01'
  raw_stage_model_name: raw_card_issuance_tsretail
  stage_model_name: v_card_issuance_tt_hsat_hub
raw_vault:
  hubs:
    - model_name: hub_card_issuance
      title: 'DV.HUB_CARD_ISSUANCE_REPORT (Хаб фактов по выдачам карт от банка)'
      parent_id_page: '2182845903' #  2422782607
      schema_name: 'DV'
      table_name: 'HUB_CARD_ISSUANCE_REPORT'
      table_desc: 'Хаб фактов по выдачам карт от банка'
      update_schedule: 'T-1'
      history_depth: ''
      src_nk: ['card_barcode', 'contract_number', 'contract_date']
  hsats:
    - model_name: hsat_card_issuance
      title: 'DV.HSAT_CARD_ISSUANCE_REPORT (Сателлит фактов по выдачам карт от банка)'
      parent_id_page: '2182845903' #  2422782607
      schema_name: 'DV'
      table_name: 'HSAT_CARD_ISSUANCE_REPORT'
      table_desc: 'Сателлит фактов по выдачам карт от банка'
      update_schedule: 'T-1'
      history_depth: ''
      src_payload: ['activation_date', 'transaction', 'card_type']
base_dm:
  mart_voice_tech_services:
      title: 'DM.CARD_ISSUANCE_REPORT (Отчет Банка по ДК/КК по выдачам карт)'
      parent_id_page: '2182845903' #  2422782607
      schema_name: 'DM'
      table_name: 'CARD_ISSUANCE_REPORT'
      table_desc: 'Отчет Банка по ДК/КК по выдачам карт'
      update_schedule: 'T-1'
      history_depth: '2026-05-01'