paths:
  output: confl/pages
  models: dbt/models
  specs: dbt/spec
  templates: confl/jnj_templates

confluence:
  source: # stage hadoop
    title: '[TEST] TSRETAIL_STG.CARD_ISSUANCE_REPORT (Отчет Банка по ДК/КК по выдачам карт)'
    table_desc: Отчет Банка по ДК/КК по выдачам карт
    template_path: hadoop/stg_hdp_page_jnj_template.html
    parent_page_id: 2182845903
    update_schedule: T-1
    history_depth: 2026-05-01
    archive_schema_table_name: tech_stg.xml_archive
    schema_name: TSRETAIL_STG
    table_name: CARD_ISSUANCE_REPORT
    message_extension: .xlsx
    system_source: wd.mtsretail.ru
    db_dtypes: hadoop

  stage:  # stage greenplum
    model_name: raw_stage_card_issuance_detailed
    title: '[TEST] STG.CARD_ISSUANCE_REPORT (Отчет Банка по ДК/КК по выдачам карт)'
    table_desc: Отчет Банка по ДК/КК по выдачам карт
    template_path: greenplum/stg_gp_page_jnj_template.html
    parent_page_id: 2182845903
    update_schedule: T-1
    history_depth: 2026-05-01
    schema_name: STG
    table_name: CARD_ISSUANCE_REPORT
    db_dtypes: greenplum

  hubs:
    - model_name: hub_card_issuance_detailed
      title: '[TEST] DV.HUB_CARD_ISSUANCE_REPORT (Хаб фактов по выдачам карт от банка)'
      table_desc: Отчет Банка по ДК/КК по выдачам карт
      template_path: greenplum/raw_vault_gp_page_jnj_template.html
      parent_page_id: 2182845903
      update_schedule: T-1
      history_depth: 2026-05-01
      schema_name: DV
      table_name: HUB_CARD_ISSUANCE_REPORT
      db_dtypes: greenplum

  hsats:
    - model_name: hsat_card_issuance_detailed
      title: '[TEST] DV.HSAT_CARD_ISSUANCE_REPORT (Сателлит фактов по выдачам карт от банка)'
      table_desc: Отчет Банка по ДК/КК по выдачам карт
      template_path: greenplum/raw_vault_gp_page_jnj_template.html
      parent_page_id: 2182845903
      update_schedule: T-1
      history_depth: 2026-05-01
      schema_name: DV
      table_name: HSAT_CARD_ISSUANCE_REPORT
      db_dtypes: greenplum

  base_marts:
    - model_name: mart_card_issuance_detailed
      title: '[TEST] DM.DM.CARD_ISSUANCE_REPORT (Отчет Банка по ДК/КК по выдачам карт)'
      table_desc: Отчет Банка по ДК/КК по выдачам карт
      template_path: greenplum/mart_gp_page_jnj_template.html
      parent_page_id: 2182845903
      update_schedule: T-1
      history_depth: 2026-05-01
      schema_name: DM
      table_name: CARD_ISSUANCE_REPORT
      db_dtypes: greenplum

  marts: # clickhouse
    - model_name: mart_card_issuance_detailed
      title: '[TEST] DEFAULT.HSAT_CARD_ISSUANCE_REPORT (Отчет Банка по ДК/КК по выдачам карт)'
      table_desc: Отчет Банка по ДК/КК по выдачам карт
      template_path: clickhouse/mart_ch_page_jnj_template.html
      parent_page_id: 2182845903
      update_schedule: T-1
      history_depth: 2026-05-01
      schema_name: DEFAULT
      table_name: CARD_ISSUANCE_REPORT
      db_dtypes: clickhouse